import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";
import Navbar from "@/components/user/Navbar";
import Searchbar from "@/components/user/Searchbar";
import Footer from "@/components/user/Footer";
import CheckUserAuth from "@/lib/CheckUserAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pet Adptation",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const getUser = await CheckUserAuth();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NextTopLoader /> */}

        <div className="bg-black ">
          <Navbar fetchUser={getUser} />
          <div className="m-2 md:m-3 lg:m-4"></div>
          {children}
        </div>
        <Footer />
        <ToastProvider />
      </body>
    </html>
  );
}
